update tsconfig
This update is done because of the error
that occured on deployment to vercel
Type error: Cannot find module '@/app/ui/fonts'
or its corresponding type declarations.